[SIS-083] Lesson Plan Editor backend
uoftblueprint/sistema pull request #110
Opened 2023-03-13 03:08 UTC by kurtislaw

# Description

Implemented getLessonPlan and deleteLessonPlan.

Also modified checkFileExists in Local.js slightly. Previous implementation would print FILE EXISTS irregardless of whether the file existed or not. Added a simple if-else to give correct response.

Ticket #

## Type of change

Please delete options that are not relevant.

- [] New feature (non-breaking change which adds functionality)
- [] Bug fix (non-breaking change which fixes an issue)
# Checklist:

- [x] My PR title is formatted as [SIS-\<issue number\>] \<issue name\> (eg. [SIS-010] Create UI button)
- [x] I have linked my issue/ticket on the project board to this PR
- [x] I have sent my PR to #team-sistema-prs on Slack and requested two people to review
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (if required)
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works

2023-03-15 23:03 UTC, ramyzhang requested changes
pls make these small changes and it'll be ready for emily to work on!! thanks for the great work kurtis!

2023-03-15 23:03 UTC, ramyzhang commented on App.js
> +// Imports for the lessonplanservice testing
pls remove tests in App.js!

2023-03-15 23:03 UTC, ramyzhang commented on src/services/routes/Local.js
> +      if (result) {
great catch!

2023-03-16 02:19 UTC, Lemiex approved these changes
Everything looks good!

2023-03-16 02:19 UTC, Lemiex commented on src/services/LessonPlanService.js
> +      } else if (await checkFileExists(defaultPath)) {
Right, it is impossible that the lesson plan is in both favouritedPath and defaultPath

2023-03-22 22:28 UTC, merged