[SIS-023] Blank LP Editor Page
uoftblueprint/sistema pull request #44
Opened 2022-12-03 16:53 UTC by Lemiex

# Description

Style basic components for the LP Editor page with dummy buttons and text input inside packages/mobile/src/editor/screens/LessonPlanEditor.js. The page is scrollable in a ScrollView
NOTE: Font is still React Native default font, not "Poppins".

Ticket #23 

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Style (formatting, missing semi colons, etc; no production code change)

# Checklist:

- [ ] My PR title is formatted as [SIS-\<issue number\>] \<issue name\> 
- [ ] I have linked my issue/ticket on the project board to this PR
- [ ] I have sent my PR to #team-sistema-prs on Slack and requested two people to review
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (if required)
- [ ] My changes generate no new warnings
- [ ] I have tested that my feature works as expected on Android and iOS. If you are a Windows dev, please request a Mac dev to run your branch. If it's a front-end change, I have attached screenshots of what the result looks like on both platforms. 
- [ ] 
<img width="660" alt="Screen Shot 2022-12-03 at 11 51 28 AM" src="https://user-images.githubusercontent.com/61687774/205452204-ed04ba2a-26c9-403c-bb32-cf8e13ef8cc5.png">
<img width="658" alt="Screen Shot 2022-12-03 at 11 52 51 AM" src="https://user-images.githubusercontent.com/61687774/205452217-4088be29-3320-438a-b8db-370aad8b0039.png">

2022-12-03 17:36 UTC, helenaglow approved these changes
Everything looks good to me! All of your code makes sense and is easy to understand. Have you tried testing it on different sized screens? I am just curious if it works the same.

2022-12-04 11:22 UTC, yuemily24 requested changes
Love love how you split up the components! Very noicely organized :) 

Not sure if it's just the screenshots, but would we be able to shift over the icons a bit more to the right? So that the margin between the back button and the RHS icons are the same. Like this. 
![headerFix](https://user-images.githubusercontent.com/76456096/205489010-b97d8be6-93cb-4af1-b341-6032a0b7a098.jpg)

Otherwise LGTM!

2022-12-04 11:22 UTC, yuemily24 commented on packages/mobile/src/editor/screens/LessonPlanEditor.js
> +const LessonPlanEditor = () => {
You'll want to keep `navigation` in here, even though it's not used right now.

2022-12-04 11:22 UTC, yuemily24 commented on packages/mobile/src/editor/screens/LessonPlanEditor.js
> +    height: 600
I would avoid setting a hard number here for `height` because screen size can change. Try using percentages.

2022-12-04 21:54 UTC, closed without merging