[SIS-073] Replace all icons with ionicons for new design system
uoftblueprint/sistema pull request #88
Opened 2023-02-01 03:56 UTC by harmitgoswami

# Description

Updated all icons to match Figma; all icons are now in the ionic style. Additionally, updated Header.js to reflect new design changes (removed hamburger icon). Also, standardized .svg file naming to camelcase.

Ticket #
SIS-073
https://github.com/uoftblueprint/sistema/issues/73

## Type of change

Please delete options that are not relevant.

- [ ] Style (formatting, missing semi colons, etc; no production code change)
- [ ] Refactor (refactoring production code, eg. renaming a variable)

# Checklist:

- [ ] My PR title is formatted as [SIS-\<issue number\>] \<issue name\> (eg. [SIS-010] Create UI button)
- [ ] I have linked my issue/ticket on the project board to this PR
- [ ] I have sent my PR to #team-sistema-prs on Slack and requested two people to review
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (if required)
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

2023-02-01 17:43 UTC, yuemily24 requested changes
I'm getting a build error where the path doesn't match the SVG file name. For example, in `App.js`, `'./assets/lessonPlanEditorNavIcon.svg'` can't be found because the SVG is still called `LessonPlanEditorNavIcon`. Please standardize all renaming. (BTW you might have to fiddle with git a bit because it doesn't detect renaming sometimes @ramyzhang might have input).

2023-02-08 00:23 UTC, ramyzhang commented
Looks great, thank you! @yuemily24 could you check if you're still getting the build error? It's working OK for me on iOS

2023-02-08 03:41 UTC, yuemily24 commented
Works for me! Can you fix merge conflicts and then let one of us know, we'll merge after

2023-02-08 03:41 UTC, yuemily24 approved these changes

2023-02-08 05:13 UTC, merged