[SIS-032] Wifi warning and unsaved changes overlays
uoftblueprint/sistema pull request #89
Opened 2023-02-07 21:19 UTC by BakerWJ

# Description

Created overlays for wifi warnings and unsaved changes.

<img width="362" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/20374181/217367990-0cfd74e2-6cb4-4b5b-a0e6-02ca8fff581a.png">

Ticket #32

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My PR title is formatted as [SIS-\<issue number\>] \<issue name\> (eg. [SIS-010] Create UI button)
- [x] I have linked my issue/ticket on the project board to this PR
- [x] I have sent my PR to #team-sistema-prs on Slack and requested two people to review
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (if required)
- [x] My changes generate no new warnings
- [ ] I have tested that my feature works as expected on Android and iOS. If you are a Windows dev, please request a Mac dev to run your branch. If it's a front-end change, I have attached screenshots of what the result looks like on both platforms.

2023-02-08 00:13 UTC, ramyzhang requested changes
Can you add more padding between the cloud icon and the text in the wifi warning? As well as in between text lines and the buttons on the bottom for both overlays? Otherwise looks good, thank you!

2023-02-08 02:54 UTC, yuemily24 requested changes
Very minor changes, otherwise looks good to me!

2023-02-08 02:54 UTC, yuemily24 commented on src/Components/Overlay.js
> +import React from 'react';
Don't think this import is needed?

2023-02-08 02:54 UTC, yuemily24 commented on src/Components/SistemaButton.js
> +import React from 'react';
Same thing

2023-02-08 02:54 UTC, yuemily24 commented on src/Components/SistemaButton.js
> +const Button = props => {
Rename to `SistemaButton`? Just for clarity

2023-02-08 02:54 UTC, yuemily24 commented on src/Components/SistemaButton.js
> +export default Button;
Don't forget to change the default export if gets changed

2023-02-08 02:54 UTC, yuemily24 commented on src/editor/screens/UnsavedChangesOverlay.js
> +import React from 'react';
Record scratch

2023-02-08 02:56 UTC, BakerWJ commented on src/editor/screens/UnsavedChangesOverlay.js
> +import React from 'react';
[IM A BOOMER IM SORRY](https://stackoverflow.com/questions/71725865/do-i-need-to-import-react-in-every-file)

2023-02-08 02:58 UTC, yuemily24 commented on src/editor/screens/UnsavedChangesOverlay.js
> +import React from 'react';
LOL all g

2023-02-15 02:24 UTC, BakerWJ commented
@ramyzhang here is picture, added a bit more margin than the og one.

<img width="363" alt="image" src="https://user-images.githubusercontent.com/20374181/218911338-a33706b8-dcf2-46a4-bcf7-b4c027b7f1bf.png">

2023-02-15 02:37 UTC, ramyzhang approved these changes
eggcellent pls do conflict resolutions and this will be good 2 go! tyty

2023-02-15 02:46 UTC, merged

2023-02-15 02:46 UTC, BakerWJ commented
i love how github says there are merge conflicts, i go to fix on my laptop and BOOOM no conflicts